/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TripType = IDL.Variant({
  'local' : IDL.Null,
  'outstation' : IDL.Null,
});
export const JourneyType = IDL.Variant({
  'roundTrip' : IDL.Null,
  'oneWay' : IDL.Null,
});
export const VehicleType = IDL.Variant({
  'suv' : IDL.Null,
  'sedan' : IDL.Null,
  'luxury' : IDL.Null,
  'hatchback' : IDL.Null,
});
export const Duration = IDL.Variant({ 'hours' : IDL.Nat, 'days' : IDL.Nat });
export const Time = IDL.Int;
export const Location = IDL.Record({
  'latitude' : IDL.Opt(IDL.Float64),
  'area' : IDL.Text,
  'longitude' : IDL.Opt(IDL.Float64),
  'pincode' : IDL.Text,
});
export const TransmissionComfort = IDL.Variant({
  'ev' : IDL.Null,
  'automatic' : IDL.Null,
  'manual' : IDL.Null,
});
export const TripStatus = IDL.Variant({
  'requested' : IDL.Null,
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
  'accepted' : IDL.Null,
});
export const Trip = IDL.Record({
  'status' : TripStatus,
  'driverId' : IDL.Opt(IDL.Principal),
  'vehicleType' : VehicleType,
  'transmissionType' : TransmissionComfort,
  'duration' : Duration,
  'tripType' : TripType,
  'dropoffLocation' : IDL.Opt(Location),
  'tripId' : IDL.Text,
  'createdTime' : Time,
  'endDateTime' : IDL.Opt(Time),
  'customerId' : IDL.Principal,
  'landmark' : IDL.Opt(IDL.Text),
  'journeyType' : JourneyType,
  'phone' : IDL.Text,
  'startDateTime' : IDL.Opt(Time),
  'pickupLocation' : Location,
});
export const AppRole = IDL.Variant({
  'admin' : IDL.Null,
  'customer' : IDL.Null,
  'driver' : IDL.Null,
});
export const LockedRole = IDL.Record({
  'role' : AppRole,
  'isLocked' : IDL.Bool,
});
export const VehicleExperience = IDL.Variant({
  'suv' : IDL.Null,
  'sedan' : IDL.Null,
  'luxury' : IDL.Null,
  'hatchback' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'serviceAreaName' : IDL.Text,
  'servicePincode' : IDL.Text,
  'role' : LockedRole,
  'vehicleExperience' : IDL.Vec(VehicleExperience),
  'languages' : IDL.Opt(IDL.Vec(IDL.Text)),
  'isAvailable' : IDL.Bool,
  'fullName' : IDL.Text,
  'createdTime' : Time,
  'email' : IDL.Text,
  'isVerified' : IDL.Opt(IDL.Bool),
  'totalEarnings' : IDL.Nat64,
  'transmissionComfort' : IDL.Vec(TransmissionComfort),
  'principalId' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptTrip' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeTrip' : IDL.Func([IDL.Text], [], []),
  'createTrip' : IDL.Func(
      [
        TripType,
        JourneyType,
        VehicleType,
        Duration,
        IDL.Opt(Time),
        IDL.Opt(Time),
        Location,
        IDL.Opt(Location),
        IDL.Text,
        IDL.Opt(IDL.Text),
        TransmissionComfort,
      ],
      [IDL.Text],
      [],
    ),
  'getAllTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
  'getRequestedTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateUserRoleAndLock' : IDL.Func([AppRole], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TripType = IDL.Variant({ 'local' : IDL.Null, 'outstation' : IDL.Null });
  const JourneyType = IDL.Variant({
    'roundTrip' : IDL.Null,
    'oneWay' : IDL.Null,
  });
  const VehicleType = IDL.Variant({
    'suv' : IDL.Null,
    'sedan' : IDL.Null,
    'luxury' : IDL.Null,
    'hatchback' : IDL.Null,
  });
  const Duration = IDL.Variant({ 'hours' : IDL.Nat, 'days' : IDL.Nat });
  const Time = IDL.Int;
  const Location = IDL.Record({
    'latitude' : IDL.Opt(IDL.Float64),
    'area' : IDL.Text,
    'longitude' : IDL.Opt(IDL.Float64),
    'pincode' : IDL.Text,
  });
  const TransmissionComfort = IDL.Variant({
    'ev' : IDL.Null,
    'automatic' : IDL.Null,
    'manual' : IDL.Null,
  });
  const TripStatus = IDL.Variant({
    'requested' : IDL.Null,
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const Trip = IDL.Record({
    'status' : TripStatus,
    'driverId' : IDL.Opt(IDL.Principal),
    'vehicleType' : VehicleType,
    'transmissionType' : TransmissionComfort,
    'duration' : Duration,
    'tripType' : TripType,
    'dropoffLocation' : IDL.Opt(Location),
    'tripId' : IDL.Text,
    'createdTime' : Time,
    'endDateTime' : IDL.Opt(Time),
    'customerId' : IDL.Principal,
    'landmark' : IDL.Opt(IDL.Text),
    'journeyType' : JourneyType,
    'phone' : IDL.Text,
    'startDateTime' : IDL.Opt(Time),
    'pickupLocation' : Location,
  });
  const AppRole = IDL.Variant({
    'admin' : IDL.Null,
    'customer' : IDL.Null,
    'driver' : IDL.Null,
  });
  const LockedRole = IDL.Record({ 'role' : AppRole, 'isLocked' : IDL.Bool });
  const VehicleExperience = IDL.Variant({
    'suv' : IDL.Null,
    'sedan' : IDL.Null,
    'luxury' : IDL.Null,
    'hatchback' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'serviceAreaName' : IDL.Text,
    'servicePincode' : IDL.Text,
    'role' : LockedRole,
    'vehicleExperience' : IDL.Vec(VehicleExperience),
    'languages' : IDL.Opt(IDL.Vec(IDL.Text)),
    'isAvailable' : IDL.Bool,
    'fullName' : IDL.Text,
    'createdTime' : Time,
    'email' : IDL.Text,
    'isVerified' : IDL.Opt(IDL.Bool),
    'totalEarnings' : IDL.Nat64,
    'transmissionComfort' : IDL.Vec(TransmissionComfort),
    'principalId' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptTrip' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeTrip' : IDL.Func([IDL.Text], [], []),
    'createTrip' : IDL.Func(
        [
          TripType,
          JourneyType,
          VehicleType,
          Duration,
          IDL.Opt(Time),
          IDL.Opt(Time),
          Location,
          IDL.Opt(Location),
          IDL.Text,
          IDL.Opt(IDL.Text),
          TransmissionComfort,
        ],
        [IDL.Text],
        [],
      ),
    'getAllTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
    'getRequestedTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateUserRoleAndLock' : IDL.Func([AppRole], [], []),
  });
};

export const init = ({ IDL }) => { return []; };