/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppRole = { 'admin' : null } |
  { 'customer' : null } |
  { 'driver' : null };
export type Duration = { 'hours' : bigint } |
  { 'days' : bigint };
export type JourneyType = { 'roundTrip' : null } |
  { 'oneWay' : null };
export interface Location {
  'latitude' : [] | [number],
  'area' : string,
  'longitude' : [] | [number],
  'pincode' : string,
}
export interface LockedRole { 'role' : AppRole, 'isLocked' : boolean }
export type Time = bigint;
export interface Trip {
  'status' : TripStatus,
  'driverId' : [] | [Principal],
  'vehicleType' : VehicleType,
  'duration' : Duration,
  'tripType' : TripType,
  'dropoffLocation' : [] | [Location],
  'tripId' : string,
  'createdTime' : Time,
  'endDateTime' : [] | [Time],
  'customerId' : Principal,
  'landmark' : [] | [string],
  'journeyType' : JourneyType,
  'phone' : string,
  'startDateTime' : [] | [Time],
  'pickupLocation' : Location,
}
export type TripStatus = { 'requested' : null } |
  { 'cancelled' : null } |
  { 'completed' : null } |
  { 'accepted' : null };
export type TripType = { 'local' : null } |
  { 'outstation' : null };
export interface UserProfile {
  'role' : LockedRole,
  'fullName' : string,
  'createdTime' : Time,
  'email' : string,
  'principalId' : Principal,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VehicleType = { 'suv' : null } |
  { 'sedan' : null } |
  { 'luxury' : null } |
  { 'hatchback' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptTrip' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeTrip' : ActorMethod<[string], undefined>,
  'createTrip' : ActorMethod<
    [
      TripType,
      JourneyType,
      VehicleType,
      Duration,
      [] | [Time],
      [] | [Time],
      Location,
      [] | [Location],
      string,
      [] | [string],
    ],
    string
  >,
  'getAllTrips' : ActorMethod<[], Array<Trip>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyTrips' : ActorMethod<[], Array<Trip>>,
  'getRequestedTrips' : ActorMethod<[], Array<Trip>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateUserRoleAndLock' : ActorMethod<[AppRole], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];