/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const VehicleType = IDL.Variant({
  'suv' : IDL.Null,
  'sedan' : IDL.Null,
  'luxury' : IDL.Null,
  'hatchback' : IDL.Null,
});
export const Duration = IDL.Variant({ 'hours' : IDL.Nat, 'days' : IDL.Nat });
export const TripType = IDL.Variant({
  'local' : IDL.Null,
  'outstation' : IDL.Null,
});
export const Location = IDL.Record({
  'latitude' : IDL.Opt(IDL.Float64),
  'area' : IDL.Text,
  'longitude' : IDL.Opt(IDL.Float64),
  'pincode' : IDL.Text,
});
export const Time = IDL.Int;
export const JourneyType = IDL.Variant({
  'roundTrip' : IDL.Null,
  'oneWay' : IDL.Null,
});
export const TripRequest = IDL.Record({
  'driverId' : IDL.Opt(IDL.Principal),
  'vehicleType' : VehicleType,
  'duration' : Duration,
  'tripType' : TripType,
  'dropoffLocation' : IDL.Opt(Location),
  'tripId' : IDL.Text,
  'totalFare' : IDL.Nat,
  'endDateTime' : IDL.Opt(Time),
  'ratePerHour' : IDL.Nat,
  'billableHours' : IDL.Nat,
  'customerId' : IDL.Opt(IDL.Principal),
  'landmark' : IDL.Opt(IDL.Text),
  'journeyType' : JourneyType,
  'phone' : IDL.Text,
  'startDateTime' : IDL.Opt(Time),
  'pickupLocation' : Location,
});
export const TripStatus = IDL.Variant({
  'requested' : IDL.Null,
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
  'accepted' : IDL.Null,
});
export const Trip = IDL.Record({
  'status' : TripStatus,
  'driverId' : IDL.Opt(IDL.Principal),
  'vehicleType' : VehicleType,
  'duration' : Duration,
  'tripType' : TripType,
  'dropoffLocation' : IDL.Opt(Location),
  'tripId' : IDL.Text,
  'totalFare' : IDL.Nat,
  'createdTime' : Time,
  'endDateTime' : IDL.Opt(Time),
  'ratePerHour' : IDL.Nat,
  'billableHours' : IDL.Nat,
  'customerId' : IDL.Principal,
  'landmark' : IDL.Opt(IDL.Text),
  'journeyType' : JourneyType,
  'phone' : IDL.Text,
  'startDateTime' : IDL.Opt(Time),
  'pickupLocation' : Location,
});
export const AppRole = IDL.Variant({
  'admin' : IDL.Null,
  'customer' : IDL.Null,
  'driver' : IDL.Null,
});
export const VehicleExperience = IDL.Variant({
  'suv' : IDL.Null,
  'sedan' : IDL.Null,
  'luxury' : IDL.Null,
  'hatchback' : IDL.Null,
});
export const TransmissionComfort = IDL.Variant({
  'ev' : IDL.Null,
  'automatic' : IDL.Null,
  'manual' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'serviceAreaName' : IDL.Text,
  'servicePincode' : IDL.Text,
  'role' : IDL.Opt(AppRole),
  'vehicleExperience' : IDL.Vec(VehicleExperience),
  'languages' : IDL.Opt(IDL.Vec(IDL.Text)),
  'isAvailable' : IDL.Bool,
  'fullName' : IDL.Text,
  'createdTime' : Time,
  'email' : IDL.Text,
  'totalEarnings' : IDL.Nat64,
  'transmissionComfort' : IDL.Vec(TransmissionComfort),
  'principalId' : IDL.Principal,
});
export const Commission = IDL.Record({
  'local' : IDL.Float64,
  'outstation' : IDL.Float64,
});
export const LocalPricing = IDL.Record({
  'per_min_after_first_hour' : IDL.Float64,
  'min_hours' : IDL.Float64,
  'base_first_hour' : IDL.Float64,
  'wait_per_min' : IDL.Float64,
  'free_wait_mins' : IDL.Float64,
});
export const VehicleMultiplier = IDL.Record({
  'suv' : IDL.Float64,
  'sedan' : IDL.Float64,
  'luxury' : IDL.Float64,
  'hatchback' : IDL.Float64,
});
export const OutstationPricing = IDL.Record({
  'commission_rate' : IDL.Float64,
  'km_slab_1_limit' : IDL.Float64,
  'km_slab_2_limit' : IDL.Float64,
  'min_days' : IDL.Float64,
  'km_slab_3_limit' : IDL.Float64,
  'per_km_slab_1' : IDL.Float64,
  'per_km_slab_2' : IDL.Float64,
  'per_km_slab_3' : IDL.Float64,
  'per_km_slab_4' : IDL.Float64,
  'driver_bata_per_day' : IDL.Float64,
  'extra_driver_comp_per_100km_over_400' : IDL.Float64,
});
export const PricingConfig = IDL.Record({
  'commission' : Commission,
  'local' : LocalPricing,
  'vehicle_multiplier' : VehicleMultiplier,
  'outstation' : OutstationPricing,
});
export const UpdateConfigResult = IDL.Variant({
  'ok' : PricingConfig,
  'failedUpdate' : IDL.Text,
  'notAdmin' : IDL.Null,
  'invalidConfig' : IDL.Text,
  'noConfigFound' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createTrip' : IDL.Func([TripRequest], [Trip], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyRole' : IDL.Func([], [IDL.Opt(AppRole)], ['query']),
  'getPricingConfig' : IDL.Func([], [PricingConfig], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'health' : IDL.Func([], [IDL.Text], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setMyRole' : IDL.Func(
      [IDL.Variant({ 'customer' : IDL.Null, 'driver' : IDL.Null })],
      [IDL.Variant({ 'ok' : IDL.Null })],
      [],
    ),
  'updatePricingConfig' : IDL.Func([PricingConfig], [UpdateConfigResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const VehicleType = IDL.Variant({
    'suv' : IDL.Null,
    'sedan' : IDL.Null,
    'luxury' : IDL.Null,
    'hatchback' : IDL.Null,
  });
  const Duration = IDL.Variant({ 'hours' : IDL.Nat, 'days' : IDL.Nat });
  const TripType = IDL.Variant({ 'local' : IDL.Null, 'outstation' : IDL.Null });
  const Location = IDL.Record({
    'latitude' : IDL.Opt(IDL.Float64),
    'area' : IDL.Text,
    'longitude' : IDL.Opt(IDL.Float64),
    'pincode' : IDL.Text,
  });
  const Time = IDL.Int;
  const JourneyType = IDL.Variant({
    'roundTrip' : IDL.Null,
    'oneWay' : IDL.Null,
  });
  const TripRequest = IDL.Record({
    'driverId' : IDL.Opt(IDL.Principal),
    'vehicleType' : VehicleType,
    'duration' : Duration,
    'tripType' : TripType,
    'dropoffLocation' : IDL.Opt(Location),
    'tripId' : IDL.Text,
    'totalFare' : IDL.Nat,
    'endDateTime' : IDL.Opt(Time),
    'ratePerHour' : IDL.Nat,
    'billableHours' : IDL.Nat,
    'customerId' : IDL.Opt(IDL.Principal),
    'landmark' : IDL.Opt(IDL.Text),
    'journeyType' : JourneyType,
    'phone' : IDL.Text,
    'startDateTime' : IDL.Opt(Time),
    'pickupLocation' : Location,
  });
  const TripStatus = IDL.Variant({
    'requested' : IDL.Null,
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const Trip = IDL.Record({
    'status' : TripStatus,
    'driverId' : IDL.Opt(IDL.Principal),
    'vehicleType' : VehicleType,
    'duration' : Duration,
    'tripType' : TripType,
    'dropoffLocation' : IDL.Opt(Location),
    'tripId' : IDL.Text,
    'totalFare' : IDL.Nat,
    'createdTime' : Time,
    'endDateTime' : IDL.Opt(Time),
    'ratePerHour' : IDL.Nat,
    'billableHours' : IDL.Nat,
    'customerId' : IDL.Principal,
    'landmark' : IDL.Opt(IDL.Text),
    'journeyType' : JourneyType,
    'phone' : IDL.Text,
    'startDateTime' : IDL.Opt(Time),
    'pickupLocation' : Location,
  });
  const AppRole = IDL.Variant({
    'admin' : IDL.Null,
    'customer' : IDL.Null,
    'driver' : IDL.Null,
  });
  const VehicleExperience = IDL.Variant({
    'suv' : IDL.Null,
    'sedan' : IDL.Null,
    'luxury' : IDL.Null,
    'hatchback' : IDL.Null,
  });
  const TransmissionComfort = IDL.Variant({
    'ev' : IDL.Null,
    'automatic' : IDL.Null,
    'manual' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'serviceAreaName' : IDL.Text,
    'servicePincode' : IDL.Text,
    'role' : IDL.Opt(AppRole),
    'vehicleExperience' : IDL.Vec(VehicleExperience),
    'languages' : IDL.Opt(IDL.Vec(IDL.Text)),
    'isAvailable' : IDL.Bool,
    'fullName' : IDL.Text,
    'createdTime' : Time,
    'email' : IDL.Text,
    'totalEarnings' : IDL.Nat64,
    'transmissionComfort' : IDL.Vec(TransmissionComfort),
    'principalId' : IDL.Principal,
  });
  const Commission = IDL.Record({
    'local' : IDL.Float64,
    'outstation' : IDL.Float64,
  });
  const LocalPricing = IDL.Record({
    'per_min_after_first_hour' : IDL.Float64,
    'min_hours' : IDL.Float64,
    'base_first_hour' : IDL.Float64,
    'wait_per_min' : IDL.Float64,
    'free_wait_mins' : IDL.Float64,
  });
  const VehicleMultiplier = IDL.Record({
    'suv' : IDL.Float64,
    'sedan' : IDL.Float64,
    'luxury' : IDL.Float64,
    'hatchback' : IDL.Float64,
  });
  const OutstationPricing = IDL.Record({
    'commission_rate' : IDL.Float64,
    'km_slab_1_limit' : IDL.Float64,
    'km_slab_2_limit' : IDL.Float64,
    'min_days' : IDL.Float64,
    'km_slab_3_limit' : IDL.Float64,
    'per_km_slab_1' : IDL.Float64,
    'per_km_slab_2' : IDL.Float64,
    'per_km_slab_3' : IDL.Float64,
    'per_km_slab_4' : IDL.Float64,
    'driver_bata_per_day' : IDL.Float64,
    'extra_driver_comp_per_100km_over_400' : IDL.Float64,
  });
  const PricingConfig = IDL.Record({
    'commission' : Commission,
    'local' : LocalPricing,
    'vehicle_multiplier' : VehicleMultiplier,
    'outstation' : OutstationPricing,
  });
  const UpdateConfigResult = IDL.Variant({
    'ok' : PricingConfig,
    'failedUpdate' : IDL.Text,
    'notAdmin' : IDL.Null,
    'invalidConfig' : IDL.Text,
    'noConfigFound' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createTrip' : IDL.Func([TripRequest], [Trip], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyRole' : IDL.Func([], [IDL.Opt(AppRole)], ['query']),
    'getPricingConfig' : IDL.Func([], [PricingConfig], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'health' : IDL.Func([], [IDL.Text], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setMyRole' : IDL.Func(
        [IDL.Variant({ 'customer' : IDL.Null, 'driver' : IDL.Null })],
        [IDL.Variant({ 'ok' : IDL.Null })],
        [],
      ),
    'updatePricingConfig' : IDL.Func([PricingConfig], [UpdateConfigResult], []),
  });
};

export const init = ({ IDL }) => { return []; };