/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Commission { 'local' : number, 'outstation' : number }
export interface DriverProfile {
  'serviceAreaName' : string,
  'updatedTime' : bigint,
  'servicePincode' : string,
  'vehicleExperience' : Array<VehicleType>,
  'languages' : Array<string>,
  'isAvailable' : boolean,
  'transmissionComfort' : Array<TransmissionType>,
}
export type Duration = { 'hours' : bigint } |
  { 'days' : bigint };
export type JourneyType = { 'roundTrip' : null } |
  { 'oneWay' : null };
export interface LocalPricing {
  'per_min_after_first_hour' : number,
  'min_hours' : number,
  'base_first_hour' : number,
  'wait_per_min' : number,
  'free_wait_mins' : number,
}
export interface Location {
  'latitude' : [] | [number],
  'area' : string,
  'longitude' : [] | [number],
  'pincode' : string,
}
export interface OutstationPricing {
  'commission_rate' : number,
  'km_slab_1_limit' : number,
  'km_slab_2_limit' : number,
  'min_days' : number,
  'km_slab_3_limit' : number,
  'per_km_slab_1' : number,
  'per_km_slab_2' : number,
  'per_km_slab_3' : number,
  'per_km_slab_4' : number,
  'driver_bata_per_day' : number,
  'extra_driver_comp_per_100km_over_400' : number,
}
export interface PricingConfig {
  'commission' : Commission,
  'local' : LocalPricing,
  'vehicle_multiplier' : VehicleMultiplier,
  'outstation' : OutstationPricing,
}
export interface ProfileInput { 'fullName' : string, 'email' : string }
export interface ProfileUpdate {
  'serviceAreaName' : string,
  'servicePincode' : string,
  'vehicleExperience' : Array<VehicleExperience>,
  'languages' : [] | [Array<string>],
  'isAvailable' : boolean,
  'fullName' : string,
  'email' : string,
  'totalEarnings' : bigint,
  'transmissionComfort' : Array<TransmissionComfort>,
}
export type Role = { 'admin' : null } |
  { 'customer' : null } |
  { 'driver' : null };
export type Time = bigint;
export type TransmissionComfort = { 'ev' : null } |
  { 'automatic' : null } |
  { 'manual' : null };
export type TransmissionType = { 'ev' : null } |
  { 'automatic' : null } |
  { 'manual' : null };
export interface Trip {
  'status' : TripStatus,
  'driverId' : [] | [Principal],
  'vehicleType' : VehicleType,
  'duration' : Duration,
  'tripType' : TripType,
  'dropoffLocation' : [] | [Location],
  'tripId' : string,
  'totalFare' : bigint,
  'createdTime' : Time,
  'endDateTime' : [] | [Time],
  'ratePerHour' : bigint,
  'billableHours' : bigint,
  'customerId' : Principal,
  'landmark' : [] | [string],
  'journeyType' : JourneyType,
  'phone' : string,
  'startDateTime' : [] | [Time],
  'pickupLocation' : Location,
}
export interface TripRequest {
  'driverId' : [] | [Principal],
  'vehicleType' : VehicleType,
  'duration' : Duration,
  'tripType' : TripType,
  'dropoffLocation' : [] | [Location],
  'tripId' : string,
  'totalFare' : bigint,
  'endDateTime' : [] | [Time],
  'ratePerHour' : bigint,
  'billableHours' : bigint,
  'customerId' : [] | [Principal],
  'landmark' : [] | [string],
  'journeyType' : JourneyType,
  'phone' : string,
  'startDateTime' : [] | [Time],
  'pickupLocation' : Location,
}
export type TripStatus = { 'requested' : null } |
  { 'cancelled' : null } |
  { 'completed' : null } |
  { 'accepted' : null };
export type TripType = { 'local' : null } |
  { 'outstation' : null };
export type UpdateConfigResult = { 'ok' : PricingConfig } |
  { 'failedUpdate' : string } |
  { 'notAdmin' : null } |
  { 'invalidConfig' : string } |
  { 'noConfigFound' : null };
export interface UserProfile {
  'serviceAreaName' : string,
  'servicePincode' : string,
  'role' : [] | [Role],
  'vehicleExperience' : Array<VehicleExperience>,
  'languages' : [] | [Array<string>],
  'isAvailable' : boolean,
  'fullName' : string,
  'createdTime' : Time,
  'email' : string,
  'totalEarnings' : bigint,
  'transmissionComfort' : Array<TransmissionComfort>,
  'principalId' : Principal,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VehicleExperience = { 'suv' : null } |
  { 'sedan' : null } |
  { 'luxury' : null } |
  { 'hatchback' : null };
export interface VehicleMultiplier {
  'suv' : number,
  'sedan' : number,
  'luxury' : number,
  'hatchback' : number,
}
export type VehicleType = { 'suv' : null } |
  { 'sedan' : null } |
  { 'luxury' : null } |
  { 'hatchback' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createTrip' : ActorMethod<[TripRequest], Trip>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDriverProfile' : ActorMethod<[], [] | [DriverProfile]>,
  'getMyRole' : ActorMethod<[], [] | [Role]>,
  'getPricingConfig' : ActorMethod<[], PricingConfig>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'health' : ActorMethod<[], string>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'ping' : ActorMethod<[], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setMyRoleCustomer' : ActorMethod<[], undefined>,
  'setMyRoleDriver' : ActorMethod<[], undefined>,
  'setProfile' : ActorMethod<[ProfileInput], UserProfile>,
  'updatePricingConfig' : ActorMethod<[PricingConfig], UpdateConfigResult>,
  'updateProfile' : ActorMethod<[ProfileUpdate], UserProfile>,
  'updateProfileFields' : ActorMethod<[string, string], UserProfile>,
  'upsertDriverProfile' : ActorMethod<[DriverProfile], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];