/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Location {
    latitude?: number;
    area: string;
    longitude?: number;
    pincode: string;
}
export interface LockedRole {
    role: AppRole;
    isLocked: boolean;
}
export interface Trip {
    status: TripStatus;
    driverId?: Principal;
    vehicleType: VehicleType;
    transmissionType: TransmissionComfort;
    duration: Duration;
    tripType: TripType;
    dropoffLocation?: Location;
    tripId: string;
    createdTime: Time;
    endDateTime?: Time;
    customerId: Principal;
    landmark?: string;
    journeyType: JourneyType;
    phone: string;
    startDateTime?: Time;
    pickupLocation: Location;
}
export type Time = bigint;
export type Duration = {
    __kind__: "hours";
    hours: bigint;
} | {
    __kind__: "days";
    days: bigint;
};
export interface UserProfile {
    serviceAreaName: string;
    servicePincode: string;
    role: LockedRole;
    vehicleExperience: Array<VehicleExperience>;
    languages?: Array<string>;
    isAvailable: boolean;
    fullName: string;
    createdTime: Time;
    email: string;
    isVerified?: boolean;
    totalEarnings: bigint;
    transmissionComfort: Array<TransmissionComfort>;
    principalId: Principal;
}
export enum AppRole {
    admin = "admin",
    customer = "customer",
    driver = "driver"
}
export enum JourneyType {
    roundTrip = "roundTrip",
    oneWay = "oneWay"
}
export enum TransmissionComfort {
    ev = "ev",
    automatic = "automatic",
    manual = "manual"
}
export enum TripStatus {
    requested = "requested",
    cancelled = "cancelled",
    completed = "completed",
    accepted = "accepted"
}
export enum TripType {
    local = "local",
    outstation = "outstation"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum VehicleExperience {
    suv = "suv",
    sedan = "sedan",
    luxury = "luxury",
    hatchback = "hatchback"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    acceptTrip(tripId: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    completeTrip(tripId: string): Promise<void>;
    createTrip(tripType: TripType, journeyType: JourneyType, vehicleType: VehicleType, duration: Duration, startDateTime: Time | null, endDateTime: Time | null, pickupLocation: Location, dropoffLocation: Location | null, phone: string, landmark: string | null, transmissionType: TransmissionComfort): Promise<string>;
    getAllTrips(): Promise<Array<Trip>>;
    getAllUsers(): Promise<Array<UserProfile>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMyTrips(): Promise<Array<Trip>>;
    getRequestedTrips(): Promise<Array<Trip>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateUserRoleAndLock(role: AppRole): Promise<void>;
}
import type { AppRole as _AppRole, Duration as _Duration, JourneyType as _JourneyType, Location as _Location, LockedRole as _LockedRole, Time as _Time, TransmissionComfort as _TransmissionComfort, Trip as _Trip, TripStatus as _TripStatus, TripType as _TripType, UserProfile as _UserProfile, UserRole as _UserRole, VehicleExperience as _VehicleExperience, VehicleType as _VehicleType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async acceptTrip(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptTrip(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptTrip(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async completeTrip(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeTrip(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeTrip(arg0);
            return result;
        }
    }
    async createTrip(arg0: TripType, arg1: JourneyType, arg2: VehicleType, arg3: Duration, arg4: Time | null, arg5: Time | null, arg6: Location, arg7: Location | null, arg8: string, arg9: string | null, arg10: TransmissionComfort): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createTrip(to_candid_TripType_n3(this._uploadFile, this._downloadFile, arg0), to_candid_JourneyType_n5(this._uploadFile, this._downloadFile, arg1), to_candid_VehicleType_n7(this._uploadFile, this._downloadFile, arg2), to_candid_Duration_n9(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg5), to_candid_Location_n12(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg7), arg8, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg9), to_candid_TransmissionComfort_n16(this._uploadFile, this._downloadFile, arg10));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTrip(to_candid_TripType_n3(this._uploadFile, this._downloadFile, arg0), to_candid_JourneyType_n5(this._uploadFile, this._downloadFile, arg1), to_candid_VehicleType_n7(this._uploadFile, this._downloadFile, arg2), to_candid_Duration_n9(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg5), to_candid_Location_n12(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg7), arg8, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg9), to_candid_TransmissionComfort_n16(this._uploadFile, this._downloadFile, arg10));
            return result;
        }
    }
    async getAllTrips(): Promise<Array<Trip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTrips();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTrips();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyTrips(): Promise<Array<Trip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTrips();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTrips();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRequestedTrips(): Promise<Array<Trip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRequestedTrips();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRequestedTrips();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n55(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n55(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateUserRoleAndLock(arg0: AppRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserRoleAndLock(to_candid_AppRole_n59(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserRoleAndLock(to_candid_AppRole_n59(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_AppRole_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppRole): AppRole {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_Duration_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Duration): Duration {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_JourneyType_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JourneyType): JourneyType {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_Location_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Location): Location {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_LockedRole_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LockedRole): LockedRole {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_TransmissionComfort_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransmissionComfort): TransmissionComfort {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_TripStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TripStatus): TripStatus {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_TripType_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TripType): TripType {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Trip_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Trip): Trip {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function from_candid_VehicleExperience_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VehicleExperience): VehicleExperience {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_VehicleType_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VehicleType): VehicleType {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Location]): Location | null {
    return value.length === 0 ? null : from_candid_Location_n33(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<string>]): Array<string> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n41(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _TripStatus;
    driverId: [] | [Principal];
    vehicleType: _VehicleType;
    transmissionType: _TransmissionComfort;
    duration: _Duration;
    tripType: _TripType;
    dropoffLocation: [] | [_Location];
    tripId: string;
    createdTime: _Time;
    endDateTime: [] | [_Time];
    customerId: Principal;
    landmark: [] | [string];
    journeyType: _JourneyType;
    phone: string;
    startDateTime: [] | [_Time];
    pickupLocation: _Location;
}): {
    status: TripStatus;
    driverId?: Principal;
    vehicleType: VehicleType;
    transmissionType: TransmissionComfort;
    duration: Duration;
    tripType: TripType;
    dropoffLocation?: Location;
    tripId: string;
    createdTime: Time;
    endDateTime?: Time;
    customerId: Principal;
    landmark?: string;
    journeyType: JourneyType;
    phone: string;
    startDateTime?: Time;
    pickupLocation: Location;
} {
    return {
        status: from_candid_TripStatus_n21(_uploadFile, _downloadFile, value.status),
        driverId: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.driverId)),
        vehicleType: from_candid_VehicleType_n24(_uploadFile, _downloadFile, value.vehicleType),
        transmissionType: from_candid_TransmissionComfort_n26(_uploadFile, _downloadFile, value.transmissionType),
        duration: from_candid_Duration_n28(_uploadFile, _downloadFile, value.duration),
        tripType: from_candid_TripType_n30(_uploadFile, _downloadFile, value.tripType),
        dropoffLocation: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.dropoffLocation)),
        tripId: value.tripId,
        createdTime: value.createdTime,
        endDateTime: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.endDateTime)),
        customerId: value.customerId,
        landmark: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.landmark)),
        journeyType: from_candid_JourneyType_n38(_uploadFile, _downloadFile, value.journeyType),
        phone: value.phone,
        startDateTime: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.startDateTime)),
        pickupLocation: from_candid_Location_n33(_uploadFile, _downloadFile, value.pickupLocation)
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    latitude: [] | [number];
    area: string;
    longitude: [] | [number];
    pincode: string;
}): {
    latitude?: number;
    area: string;
    longitude?: number;
    pincode: string;
} {
    return {
        latitude: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.latitude)),
        area: value.area,
        longitude: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.longitude)),
        pincode: value.pincode
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    serviceAreaName: string;
    servicePincode: string;
    role: _LockedRole;
    vehicleExperience: Array<_VehicleExperience>;
    languages: [] | [Array<string>];
    isAvailable: boolean;
    fullName: string;
    createdTime: _Time;
    email: string;
    isVerified: [] | [boolean];
    totalEarnings: bigint;
    transmissionComfort: Array<_TransmissionComfort>;
    principalId: Principal;
}): {
    serviceAreaName: string;
    servicePincode: string;
    role: LockedRole;
    vehicleExperience: Array<VehicleExperience>;
    languages?: Array<string>;
    isAvailable: boolean;
    fullName: string;
    createdTime: Time;
    email: string;
    isVerified?: boolean;
    totalEarnings: bigint;
    transmissionComfort: Array<TransmissionComfort>;
    principalId: Principal;
} {
    return {
        serviceAreaName: value.serviceAreaName,
        servicePincode: value.servicePincode,
        role: from_candid_LockedRole_n43(_uploadFile, _downloadFile, value.role),
        vehicleExperience: from_candid_vec_n47(_uploadFile, _downloadFile, value.vehicleExperience),
        languages: record_opt_to_undefined(from_candid_opt_n49(_uploadFile, _downloadFile, value.languages)),
        isAvailable: value.isAvailable,
        fullName: value.fullName,
        createdTime: value.createdTime,
        email: value.email,
        isVerified: record_opt_to_undefined(from_candid_opt_n50(_uploadFile, _downloadFile, value.isVerified)),
        totalEarnings: value.totalEarnings,
        transmissionComfort: from_candid_vec_n51(_uploadFile, _downloadFile, value.transmissionComfort),
        principalId: value.principalId
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    role: _AppRole;
    isLocked: boolean;
}): {
    role: AppRole;
    isLocked: boolean;
} {
    return {
        role: from_candid_AppRole_n45(_uploadFile, _downloadFile, value.role),
        isLocked: value.isLocked
    };
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    requested: null;
} | {
    cancelled: null;
} | {
    completed: null;
} | {
    accepted: null;
}): TripStatus {
    return "requested" in value ? TripStatus.requested : "cancelled" in value ? TripStatus.cancelled : "completed" in value ? TripStatus.completed : "accepted" in value ? TripStatus.accepted : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    suv: null;
} | {
    sedan: null;
} | {
    luxury: null;
} | {
    hatchback: null;
}): VehicleExperience {
    return "suv" in value ? VehicleExperience.suv : "sedan" in value ? VehicleExperience.sedan : "luxury" in value ? VehicleExperience.luxury : "hatchback" in value ? VehicleExperience.hatchback : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ev: null;
} | {
    automatic: null;
} | {
    manual: null;
}): TransmissionComfort {
    return "ev" in value ? TransmissionComfort.ev : "automatic" in value ? TransmissionComfort.automatic : "manual" in value ? TransmissionComfort.manual : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hours: bigint;
} | {
    days: bigint;
}): {
    __kind__: "hours";
    hours: bigint;
} | {
    __kind__: "days";
    days: bigint;
} {
    return "hours" in value ? {
        __kind__: "hours",
        hours: value.hours
    } : "days" in value ? {
        __kind__: "days",
        days: value.days
    } : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    local: null;
} | {
    outstation: null;
}): TripType {
    return "local" in value ? TripType.local : "outstation" in value ? TripType.outstation : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    roundTrip: null;
} | {
    oneWay: null;
}): JourneyType {
    return "roundTrip" in value ? JourneyType.roundTrip : "oneWay" in value ? JourneyType.oneWay : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    customer: null;
} | {
    driver: null;
}): AppRole {
    return "admin" in value ? AppRole.admin : "customer" in value ? AppRole.customer : "driver" in value ? AppRole.driver : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Trip>): Array<Trip> {
    return value.map((x)=>from_candid_Trip_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n41(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VehicleExperience>): Array<VehicleExperience> {
    return value.map((x)=>from_candid_VehicleExperience_n48(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TransmissionComfort>): Array<TransmissionComfort> {
    return value.map((x)=>from_candid_TransmissionComfort_n26(_uploadFile, _downloadFile, x));
}
function to_candid_AppRole_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): _AppRole {
    return to_candid_variant_n60(_uploadFile, _downloadFile, value);
}
function to_candid_Duration_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Duration): _Duration {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_JourneyType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JourneyType): _JourneyType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Location_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Location): _Location {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_LockedRole_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LockedRole): _LockedRole {
    return to_candid_record_n58(_uploadFile, _downloadFile, value);
}
function to_candid_TransmissionComfort_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransmissionComfort): _TransmissionComfort {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_TripType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TripType): _TripType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n56(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_VehicleExperience_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleExperience): _VehicleExperience {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_VehicleType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleType): _VehicleType {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Time | null): [] | [_Time] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Location | null): [] | [_Location] {
    return value === null ? candid_none() : candid_some(to_candid_Location_n12(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    latitude?: number;
    area: string;
    longitude?: number;
    pincode: string;
}): {
    latitude: [] | [number];
    area: string;
    longitude: [] | [number];
    pincode: string;
} {
    return {
        latitude: value.latitude ? candid_some(value.latitude) : candid_none(),
        area: value.area,
        longitude: value.longitude ? candid_some(value.longitude) : candid_none(),
        pincode: value.pincode
    };
}
function to_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    serviceAreaName: string;
    servicePincode: string;
    role: LockedRole;
    vehicleExperience: Array<VehicleExperience>;
    languages?: Array<string>;
    isAvailable: boolean;
    fullName: string;
    createdTime: Time;
    email: string;
    isVerified?: boolean;
    totalEarnings: bigint;
    transmissionComfort: Array<TransmissionComfort>;
    principalId: Principal;
}): {
    serviceAreaName: string;
    servicePincode: string;
    role: _LockedRole;
    vehicleExperience: Array<_VehicleExperience>;
    languages: [] | [Array<string>];
    isAvailable: boolean;
    fullName: string;
    createdTime: _Time;
    email: string;
    isVerified: [] | [boolean];
    totalEarnings: bigint;
    transmissionComfort: Array<_TransmissionComfort>;
    principalId: Principal;
} {
    return {
        serviceAreaName: value.serviceAreaName,
        servicePincode: value.servicePincode,
        role: to_candid_LockedRole_n57(_uploadFile, _downloadFile, value.role),
        vehicleExperience: to_candid_vec_n61(_uploadFile, _downloadFile, value.vehicleExperience),
        languages: value.languages ? candid_some(value.languages) : candid_none(),
        isAvailable: value.isAvailable,
        fullName: value.fullName,
        createdTime: value.createdTime,
        email: value.email,
        isVerified: value.isVerified ? candid_some(value.isVerified) : candid_none(),
        totalEarnings: value.totalEarnings,
        transmissionComfort: to_candid_vec_n63(_uploadFile, _downloadFile, value.transmissionComfort),
        principalId: value.principalId
    };
}
function to_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    role: AppRole;
    isLocked: boolean;
}): {
    role: _AppRole;
    isLocked: boolean;
} {
    return {
        role: to_candid_AppRole_n59(_uploadFile, _downloadFile, value.role),
        isLocked: value.isLocked
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "hours";
    hours: bigint;
} | {
    __kind__: "days";
    days: bigint;
}): {
    hours: bigint;
} | {
    days: bigint;
} {
    return value.__kind__ === "hours" ? {
        hours: value.hours
    } : value.__kind__ === "days" ? {
        days: value.days
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransmissionComfort): {
    ev: null;
} | {
    automatic: null;
} | {
    manual: null;
} {
    return value == TransmissionComfort.ev ? {
        ev: null
    } : value == TransmissionComfort.automatic ? {
        automatic: null
    } : value == TransmissionComfort.manual ? {
        manual: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TripType): {
    local: null;
} | {
    outstation: null;
} {
    return value == TripType.local ? {
        local: null
    } : value == TripType.outstation ? {
        outstation: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JourneyType): {
    roundTrip: null;
} | {
    oneWay: null;
} {
    return value == JourneyType.roundTrip ? {
        roundTrip: null
    } : value == JourneyType.oneWay ? {
        oneWay: null
    } : value;
}
function to_candid_variant_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): {
    admin: null;
} | {
    customer: null;
} | {
    driver: null;
} {
    return value == AppRole.admin ? {
        admin: null
    } : value == AppRole.customer ? {
        customer: null
    } : value == AppRole.driver ? {
        driver: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleExperience): {
    suv: null;
} | {
    sedan: null;
} | {
    luxury: null;
} | {
    hatchback: null;
} {
    return value == VehicleExperience.suv ? {
        suv: null
    } : value == VehicleExperience.sedan ? {
        sedan: null
    } : value == VehicleExperience.luxury ? {
        luxury: null
    } : value == VehicleExperience.hatchback ? {
        hatchback: null
    } : value;
}
function to_candid_vec_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<VehicleExperience>): Array<_VehicleExperience> {
    return value.map((x)=>to_candid_VehicleExperience_n62(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<TransmissionComfort>): Array<_TransmissionComfort> {
    return value.map((x)=>to_candid_TransmissionComfort_n16(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
